#Based on https://ci.salto.io/ && https://sfdx-hardis.cloudity.com/
on:
  pull_request:
    branches: [ main ]
    types: [closed]
    paths:
      - 'force-app/**'
      
name: Deploy SFDX Hardis

jobs:
  prod_deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    name: Deployment to Major Org
    permissions:
      pull-requests: write
    steps:
    # Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Faster code checkout fetching only latest commit
    # Setup node
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    # tests to run
    - name: 'Selecting Tests to Run from PR Body'
      env:
        PR_BODY: ${{github.event.pull_request.body}}´
      run: |
        echo $PR_BODY > ./pr_body.txt
        node ./parsePR.js   
        cat testsToRun.txt           
        TESTS=$(cat testsToRun.txt)       
        echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV    
    # SFDX & plugins
    - name: Install SFDX and plugins
      run: |
        npm install --no-cache @salesforce/cli --global
        sf plugins install @salesforce/plugin-packaging
        echo 'y' | sfdx plugins:install sfdx-hardis
        echo 'y' | sfdx plugins:install sfdx-git-delta
        sf version --verbose --json
    # Calculate delta and set package.xml = delta.xml to deploy only delta changes
    - name: Configure delta changes for sfdx-hardis
      run: |
        mkdir changed-sources
        sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/
        echo $(cat changed-sources/package/package.xml) > manifest/package.xml
    # Login & check deploy runnning All Tests
    - name: Login & Simulate delta deployment - All Tests
      env:
        SFDX_CLIENT_ID_MAIN: ${{ secrets.SFDX_CLIENT_ID_MAIN}}
        SFDX_CLIENT_KEY_MAIN: ${{ secrets.SFDX_CLIENT_KEY_MAIN}}
        SFDX_DEPLOY_WAIT_MINUTES: 120 # Override if necessary
        SFDX_TEST_WAIT_MINUTES: 120 # Override if necessary
        CI_COMMIT_REF_NAME: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
        ORG_ALIAS: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
        CONFIG_BRANCH: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FORCE_COLOR: "1"
      if: ${{env.APEX_TESTS == 'all'}}
      run: |
        sfdx hardis:auth:login
        sfdx hardis:project:deploy:sources:dx   
    # Login & check deploy runnning Selected Tests
    - name: Login & Simulate delta deployment - Selected Tests
      if: ${{env.APEX_TESTS != 'all'}}
      env:
        SFDX_CLIENT_ID_MAIN: ${{ secrets.SFDX_CLIENT_ID_MAIN}}
        SFDX_CLIENT_KEY_MAIN: ${{ secrets.SFDX_CLIENT_KEY_MAIN}}
        SFDX_DEPLOY_WAIT_MINUTES: 120 # Override if necessary
        SFDX_TEST_WAIT_MINUTES: 120 # Override if necessary
        CI_COMMIT_REF_NAME: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
        ORG_ALIAS: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
        CONFIG_BRANCH: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FORCE_COLOR: "1"
      run: |
        sfdx hardis:auth:login
        sfdx hardis:project:deploy:sources:dx -l RunSpecifiedTests -r ${{env.APEX_TESTS}}

    - name: 'Deploy destructive changes (if any)'
      run: sfdx force:mdapi:deploy -d "changed-sources/destructiveChanges" --ignorewarnings 